import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavbarComponent from "@/components/share/menubar";

const font = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SMP NEGERI 1 DOBO",
  description: "Generated by create next app",
};

export default function LandingPageLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div
      className={`${font.className} overflow-x-hidden bg-hero 2xl:px-[200px] px-6 h-full min-h-screen`}
    >
      <NavbarComponent />
      {children}
    </div>
  );
}
